#pragma once

#include <cassert>
#include <optional>
#include <ostream>
#include <span>
#include <string>
#include <string_view>
#include <variant>
#include <vector>
#include <stdexcept>
#include <memory>

#include "utils.hpp"

using std::optional;
using std::nullopt;
using std::string;
using std::string_view;
using std::variant;
using std::vector;
using std::span;


//==============================================================================
// Tokens
//==============================================================================
enum class Lexeme
{
	IDENTIFIER,
	INT_LITERAL,
	C_STRING_LITERAL,
	TRUE,
	FALSE,

	DOT,
	COMMA,
	COLON,
	SEMICOLON,
	CIRCUMFLEX,
	AMPERSAND,
	QUESTIONMARK,
	BANG,
	SINGLE_QUOTE,
	AT,
	BAR,
	LEFT_PAREN,
	RIGHT_PAREN,
	LEFT_BRACE,
	RIGHT_BRACE,
	LEFT_BRACKET,
	RIGHT_BRACKET,

	THIN_ARROW,

	PLUS,
	MINUS,
	UNARY_MINUS, // Not actually generated by the lexer. Only used for get_operator_info()
	SLASH,
	STAR,
	EQ,
	COLON_EQ,
	DOUBLE_EQ,
	LT,
	LE,
	GT,
	GE,

	NOT,

	LET,
	PROC,
	STRUCT,
	CASE,
	IMPLICIT,

	TYPE_NEVER,
	TYPE_BOOL,
	TYPE_UNIT,
	TYPE_I8,
	TYPE_U8,
	TYPE_I32,
	TYPE_U32,
	TYPE_ISIZE,
	TYPE_USIZE,

	IF,
	ELSE,
	WHILE,
	MATCH,
	RETURN,

	AS,
	MUT,

	TYPEALIAS,
	EXTERN,

	SIZE_OF,
	MAKE,

	END,
};

struct SourceLocation
{
	size_t pos = 0;
	int line = 0;
	int col = 0;
};

struct SourceSpan
{
	SourceLocation begin;
	SourceLocation end;
};

struct Token
{
	Lexeme kind;

	union
	{
		uint64_t int_val{};
		string_view str_val;
	} value{};

	SourceSpan span;
};

string_view str(Lexeme tok);
inline string str(SourceLocation loc) { return std::to_string(loc.line) + ":" + std::to_string(loc.col); }

struct TokenIdx { uint32_t value; };
struct TokenRange { TokenIdx first{}, last{}; };

inline constexpr TokenIdx INVALID_TOKEN_IDX = TokenIdx(-1);
inline constexpr TokenRange UNKNOWN_TOKEN_RANGE = TokenRange(INVALID_TOKEN_IDX, INVALID_TOKEN_IDX);


//==============================================================================
// AST
//==============================================================================

//--------------------------------------------------------------------
// Types
//--------------------------------------------------------------------
struct Module;
class StructInstance;
class ProcInstance;
class UnionInstance;
struct StructItem;
struct ProcTypeInstance;
struct TypeParameter;
struct Expr;

struct TypeParameterVar
{
	TokenRange range;
	TypeParameter const *def;
};

struct TypeDeductionVar
{
	uint32_t id;

	friend bool operator == (TypeDeductionVar, TypeDeductionVar) = default;
};

using VarType = variant<TypeParameterVar, TypeDeductionVar>;

using Type = variant
<
	struct BuiltinType,
	struct KnownIntType,
	struct PointerType,
	struct ProcType,
	struct StructType,
	struct UnionType,
	VarType,

	// Unresolved types
	struct Path,
	struct ProcTypeUnresolved,
	struct UnionTypeUnresolved,
	struct InlineStructType
>;

enum class BuiltinTypeDef
{
	NEVER,
	UNIT,
	BOOL,
	I8,
	U8,
	I32,
	U32,
	ISIZE,
	USIZE,
};

struct BuiltinType
{
	TokenRange range;
	BuiltinTypeDef builtin;
};

struct KnownIntType
{
	Int128 low;
	Int128 high;
};

struct Path
{
	TokenRange range;
	FixedArray<Type> *type_args = nullptr;
	Path *NULLABLE child = nullptr;
};

enum class IsMutable
{
	YES,
	NO,
};

struct PointerType
{
	enum Kind
	{
		SINGLE,
		MANY,
	};

	TokenRange range;
	Type *pointee;
	Kind kind;
	IsMutable mutability;
};

struct UnionTypeUnresolved
{
	TokenRange range;
	FixedArray<Type> *alternatives = nullptr;
};

struct UnionType
{
	TokenRange range;
	UnionInstance *inst;
};

struct ProcTypeUnresolved
{
	TokenRange range;
	Type *ret;
	FixedArray<Type> *params = nullptr;
};


struct NoDefaultValue {};
struct ExprPending {};

struct DefaultValueExpr : variant<NoDefaultValue, ExprPending, Expr*>
{
	using variant::variant;

	Expr* try_get_expr() const
	{
		return *this | match
		{
			[](Expr *expr) { return expr; },
			[](auto) { return (Expr*)nullptr; },
		};
	}

	NO_DANGLING Expr& get_expr() const
	{
		Expr *expr = try_get_expr();
		assert(expr && "DefaultValueExpr has no expr");
		return *expr;
	}

	explicit operator bool () const
	{
		return *this | match
		{
			[](NoDefaultValue) { return false; },
			[](auto) { return true; },
		};
	}
};

struct ProcType
{
	TokenRange range;
	ProcTypeInstance *inst;

	// This is used for typechecking procedure/constructor calls, but is irrelevant for deciding
	// whether two ProcTypes are equal.
	variant<ProcInstance*, StructInstance*> callable;

	size_t param_count() const;
	Type* param_type_at(size_t idx) const;
	string_view param_name_at(size_t idx) const;
	DefaultValueExpr param_default_value_at(size_t idx) const;
};


struct StructType
{
	TokenRange range;
	StructInstance *inst;
};

struct InlineStructType
{
	TokenRange range;
	StructItem *struct_;
};

static_assert(sizeof(Type) == 48, "sizeof(Type) is getting larger...");

string_view name_of(Path const &path, Module const *mod);
void print(Path const &path, Module const &mod, std::ostream &os);
void print(VarType const &var, std::ostream &os);
void print(Type const &type, Module const &mod, std::ostream &os);
string str(Type const &type, Module const &mod);
TokenRange token_range_of(Type const &type);


template<>
struct std::hash<TypeDeductionVar>
{
	size_t operator () (TypeDeductionVar var) const
	{
		return compute_hash(var.id);
	}
};

template<>
struct std::hash<::VarType>
{
	size_t operator () (::VarType var) const
	{
		size_t h = ::compute_hash(var.index());
		var | ::match
		{
			[&](TypeParameterVar v)
			{
				::combine_hashes(h, ::compute_hash(v.def));
			},
			[&](TypeDeductionVar v)
			{
				::combine_hashes(h, ::compute_hash(v));
			},
		};

		return h;
	}
};

inline bool operator == (VarType const &a, VarType const &b)
{
	if(a.index() != b.index())
		return false;

	return a | match
	{
		[&](TypeParameterVar const &p) { return p.def == std::get<TypeParameterVar>(b).def; },
		[&](TypeDeductionVar const &d) { return d.id == std::get<TypeDeductionVar>(b).id; },
	};
}

template<>
struct std::hash<Type>
{
	size_t operator () (Type const &type) const
	{
		size_t h = compute_hash(type.index());
		type | match
		{
			[&](BuiltinType const &t)
			{
				::combine_hashes(h, compute_hash((int)t.builtin));
			},
			[&](KnownIntType const &t)
			{
				::combine_hashes(h, compute_hash(t.low));
				::combine_hashes(h, compute_hash(t.high));
			},
			[&](VarType const &t)
			{
				::combine_hashes(h, compute_hash(t));
			},
			[&](PointerType const &t)
			{
				::combine_hashes(h, compute_hash((int)t.kind));
				::combine_hashes(h, compute_hash((int)t.mutability));
				::combine_hashes(h, compute_hash(*t.pointee));
			},
			[&](StructType const &t)
			{
				::combine_hashes(h, compute_hash(t.inst));
			},
			[&](ProcType const &t)
			{
				::combine_hashes(h, compute_hash(t.inst));
			},
			[&](UnionType const &t)
			{
				::combine_hashes(h, compute_hash(t.inst));
			},
			[&](ProcTypeUnresolved const&) { assert(!"hash<Type>: ProcTypeUnresolved"); },
			[&](UnionTypeUnresolved const&) { assert(!"hash<Type>: UnionTypeUnresolved"); },
			[&](Path const&) { assert(!"hash<Type>: Path"); },
			[&](InlineStructType const&) { assert(!"hash<Type>: InlineStructType"); },
		};

		return h;
	}
};


//--------------------------------------------------------------------
// Expressions
//--------------------------------------------------------------------
struct Expr;
struct Var;
class ProcInstance;

struct IntLiteralExpr
{
	TokenRange range;
	Int128 value;

	Type *NULLABLE type = nullptr;
};

struct BoolLiteralExpr
{
	TokenRange range;
	bool value;

	Type *NULLABLE type = nullptr;
};

enum class StringLiteralKind
{
	C
};

struct StringLiteralExpr
{
	TokenRange range;
	StringLiteralKind kind;
	string_view value;

	Type *NULLABLE type = nullptr;
};

enum class UnaryOp
{
	NOT = int(Lexeme::NOT),
	NEG = int(Lexeme::MINUS),
};

struct UnaryExpr
{
	TokenRange range;
	Expr *sub;
	UnaryOp op;

	Type *NULLABLE type = nullptr;
};

enum class BinaryOp
{
	ADD = int(Lexeme::PLUS),
	SUB = int(Lexeme::MINUS),
	MUL = int(Lexeme::STAR),
	DIV = int(Lexeme::SLASH),

	EQ = int(Lexeme::DOUBLE_EQ),
	LT = int(Lexeme::LT),
	LE = int(Lexeme::LE),
	GT = int(Lexeme::GT),
	GE = int(Lexeme::GE),
};

struct BinaryExpr
{
	TokenRange range;
	Expr *left;
	Expr *right;
	BinaryOp op;

	Type *NULLABLE type = nullptr;
};

// The current syntax for taking a mutable address is `&mut var`, which is quite long.
// Potential alternatives:
// - Ditch `mut`: If `var` is mutable, then `&var` results in a mutable pointer
// - Replace `&mut` with `!`: `&var` results in a constant pointer, while `!var` results in a
//   mutable pointer
struct AddressOfExpr
{
	TokenRange range;
	Expr *object;
	IsMutable mutability;

	Type *NULLABLE type = nullptr;
};

struct DerefExpr
{
	TokenRange range;
	Expr *addr;

	Type *NULLABLE type = nullptr;
};

struct IndexExpr
{
	TokenRange range;
	Expr *addr;
	Expr *index;

	Type *NULLABLE type = nullptr;
};

struct MemberAccessExpr
{
	TokenRange range;
	Expr *object;
	string_view member;

	Type *NULLABLE type = nullptr;
};

struct AssignmentExpr
{
	TokenRange range;
	Expr *lhs;
	Expr *rhs;

	Type *NULLABLE type = nullptr;
};

struct AsExpr
{
	TokenRange range;
	Expr *src_expr;
	Type *target_type;

	Type *NULLABLE type = nullptr;
};

struct ConstructorExpr
{
	TokenRange range;
	Type *ctor;

	Type *NULLABLE type = nullptr;
};

struct ProcExpr
{
	TokenRange range;
	ProcInstance *inst;

	Type *NULLABLE type = nullptr;
};

struct CallExpr
{
	TokenRange range;
	Expr *callable;
	FixedArray<struct Argument> *args;

	Type *NULLABLE type = nullptr;
};

struct SizeOfExpr
{
	TokenRange range;
	Type *subject;

	Type *NULLABLE type = nullptr;
};

struct MakeExpr
{
	TokenRange range;
	Expr *init;
	Expr *addr;

	Type *NULLABLE type = nullptr;
};

struct VarExpr
{
	TokenRange range;
	Var const *NULLABLE var = nullptr;

	Type *NULLABLE type = nullptr;
};

struct UnionInitExpr
{
	TokenRange range;
	Expr *alt_expr;

	// We have to store the alt_type instead of the alt_idx here because the order of the
	// alternatives may change during substitution. Additinally, some alternatives may be removed
	// if it turns out they are duplicates.
	Type *alt_type;

	Type *NULLABLE type = nullptr;
};

struct Expr : variant<
	IntLiteralExpr,
	BoolLiteralExpr,
	StringLiteralExpr,
	UnaryExpr,
	BinaryExpr,
	AddressOfExpr,
	DerefExpr,
	IndexExpr,
	MemberAccessExpr,
	AssignmentExpr,
	AsExpr,
	ConstructorExpr,
	ProcExpr,
	CallExpr,
	SizeOfExpr,
	MakeExpr,
	VarExpr,
	UnionInitExpr,
	Path
>
{
	using variant::variant;
};

struct Argument
{
	TokenRange range;
	Expr expr;
	string_view name{}; // May be empty

	int param_idx = 0; // Available after semantic analysis
};

void print(Expr const &expr, Module const &mod, std::ostream &os);
Type* type_of(Expr &expr);
Type const* type_of(Expr const &expr);
TokenRange token_range_of(Expr const &expr);

static_assert(sizeof(Expr) == 64, "sizeof(Expr) is getting larger...");


//--------------------------------------------------------------------
// Patterns
//--------------------------------------------------------------------
struct Pattern;

struct DerefPattern
{
	TokenRange range;
	Pattern *sub;

	Type *NULLABLE type = nullptr;
};

struct AddressOfPattern
{
	TokenRange range;
	Pattern *sub;
	IsMutable mutability;

	Type *NULLABLE type = nullptr;
};

struct VarPatternUnresolved
{
	TokenRange range;
	string_view name;
	IsMutable mutability;
};

struct VarPattern
{
	TokenRange range;
	Var *var = nullptr;

	Type *NULLABLE type = nullptr;
};

struct WildcardPattern
{
	TokenRange range;
	Type *NULLABLE type = nullptr;
};

struct ConstructorPattern
{
	TokenRange range;
	Type *ctor;
	FixedArray<struct PatternArgument> *args;
	bool has_parens;

	Type *NULLABLE type = nullptr;
};


struct Pattern : variant
<
	VarPatternUnresolved,
	VarPattern,
	DerefPattern,
	AddressOfPattern,
	ConstructorPattern,
	WildcardPattern
>
{
	template<typename T>
	Pattern(T &&t, Type *NULLABLE provided_type) :
		variant(std::forward<T>(t)),
		provided_type(provided_type) {}

	Type *NULLABLE provided_type;
};

struct PatternArgument
{
	Pattern pattern;
	string_view param_name; // May be empty

	int param_idx = 0; // Available after semantic analysis
};

TokenRange token_range_of(Pattern const &pattern);
Type& type_of(Pattern &pattern);
Type const& type_of(Pattern const &pattern);
void print(Pattern const &pattern, Module const &mod, std::ostream &os);

static_assert(sizeof(Pattern) == 56, "sizeof(Pattern) is getting larger...");


//--------------------------------------------------------------------
// Statements
//--------------------------------------------------------------------
using Stmt = variant<
	struct LetStmt,
	struct ExprStmt,
	struct BlockStmt,
	struct ReturnStmt,
	struct IfStmt,
	struct WhileStmt,
	struct MatchStmt
>;

struct LetStmt
{
	TokenRange range;
	Pattern *lhs;
	Expr *init_expr;
};

struct ExprStmt
{
	TokenRange range;
	Expr *expr;
};

struct BlockStmt
{
	TokenRange range;
	FixedArray<Stmt> *stmts;
};

struct ReturnStmt
{
	TokenRange range;
	Expr *NULLABLE ret_expr = nullptr;
};

struct IfStmt
{
	TokenRange range;
	Expr *condition;
	Stmt *then;
	Stmt *NULLABLE else_ = nullptr;
};

struct WhileStmt
{
	TokenRange range;
	Expr *condition;
	Stmt *body;
};


struct MatchStmt
{
	TokenRange range;
	Expr *expr;
	FixedArray<struct MatchArm> *arms;
};

struct MatchArm
{
	Pattern capture;
	Stmt stmt;

	// Available after semantic analysis
	int discr = -1;
};


void print(Stmt const &stmt, Module const &mod, std::ostream &os);

static_assert(sizeof(Stmt) == 40, "sizeof(Stmt) is getting larger...");


//--------------------------------------------------------------------
// Top-level items
//--------------------------------------------------------------------
struct SemaModule;
struct Struct;
struct Proc;
struct Alias;

struct Parameter
{
	TokenRange range;
	Type *NULLABLE type = nullptr;
	DefaultValueExpr default_value;
};

struct TypeParameter
{
	TokenRange range;
	string_view name;
};

struct ProcItem
{
	TokenRange range;
	string_view name;
	string_view receiver_name; // May be empty
	FixedArray<TypeParameter> *type_params = nullptr;
	FixedArray<Parameter> *params = nullptr;
	Type *NULLABLE ret_type = nullptr;
	Stmt *NULLABLE body = nullptr;
	bool is_extern = false;

	Proc *NULLABLE sema = nullptr; // Available after semantic analysis
};

struct StructMember { struct StructItem *struct_; };
struct CaseMember { struct StructItem *struct_; };
// using Member = variant<Parameter, StructMember, CaseMember>; TODO Use this
using Member = variant<Parameter, StructItem*>;

struct StructItem
{
	TokenRange range;
	string_view name;
	FixedArray<TypeParameter> *type_params = nullptr;
	FixedArray<Member> *members = nullptr;
	bool is_implicit = false;
	bool ctor_without_parens = false;
	bool is_extern = false;
	int num_case_members = 0;
	bool is_case_member = false;

	int num_var_members() const { return members->count - num_case_members; }
	bool has_constructor() const { return num_case_members == 0; }

	Struct *NULLABLE sema = nullptr; // Available after semantic analysis
};

struct AliasItem
{
	TokenRange range;
	string_view name;
	FixedArray<TypeParameter> *type_params = nullptr;
	Type *aliased_type;

	Alias *NULLABLE sema = nullptr; // Available after semantic analysis
};

using TopLevelItem = variant<
	ProcItem,
	StructItem,
	AliasItem
>;


//==============================================================================
// Lexing
//==============================================================================
class LexingError : public std::runtime_error
{
public:
	explicit LexingError(string const &msg) :
		std::runtime_error{msg} {}
};

class Lexer
{
public:
	Lexer(
		string_view source,
		SourceLocation initial_location = {.pos = 0, .line = 1, .col = 1}
	) :
		m_source{source},
		m_initial_byte_pos{initial_location.pos},
		m_byte_pos{0},
		m_line{initial_location.line},
		m_column{initial_location.col} {}

	string_view source() const {
		return m_source;
	}

	size_t local_byte_pos() const {
		return m_byte_pos;
	}

	size_t initial_byte_pos() const {
		return m_initial_byte_pos;
	}

	char get()
	{
		assert(m_byte_pos < m_source.length());
		return m_source[m_byte_pos];
	}

	SourceLocation location() const
	{
		return SourceLocation{
			.pos = m_initial_byte_pos + m_byte_pos,
			.line = m_line,
			.col = m_column,
		};
	}

	string_view remaining_string() const {
		return {m_source.begin() + m_byte_pos, m_source.end()};
	}

	// Returns the substring from start_pos to the current position
	string_view substr_from(size_t start_pos) const {
		return m_source.substr(start_pos, m_byte_pos - start_pos);
	}

	bool has_more(size_t how_many = 1) const {
		return m_byte_pos + how_many <= m_source.length();
	}

	void advance(size_t n = 1)
	{
		while(n-- && has_more())
		{
			if(m_source[m_byte_pos] == '\n')
			{
				m_line += 1;
				m_column = 1;
			}
			else
				m_column += 1;

			m_byte_pos += 1;
		}
	}

private:
	string_view m_source;
	size_t m_initial_byte_pos;
	size_t m_byte_pos;
	int m_line;
	int m_column;
};

void skip_whitespace(Lexer &lexer);
void consume(Lexer &lexer, string_view expected_str);
bool try_consume(Lexer &lexer, string_view expected_str);
optional<string_view> try_read_identifier(Lexer &lexer);
optional<uint64_t> try_read_number(Lexer &lexer);
optional<Token> next_token(Lexer &lex);


//==============================================================================
// Parsing
//==============================================================================
class ParseError : public std::runtime_error
{
public:
	ParseError(std::string const &msg) :
		std::runtime_error{msg} {}
};

class Parser
{
public:
	Parser() = default;

	explicit Parser(string_view source)
	{
		append_source(source);
		fetch_tokens_until(m_token_pos);
	}

	Token const& get() const
	{
		if (m_token_pos < m_tokens.size())
			return m_tokens[m_token_pos];

		return m_end_token;
	}

	Token const& token_at(TokenIdx idx) const
	{
		if (idx.value < m_tokens.size())
			return m_tokens[idx.value];

		return m_end_token;
	}

	Token const& next()
	{
		fetch_tokens_until(m_token_pos + 1);
		if (m_token_pos < m_tokens.size())
			return m_tokens[m_token_pos++];

		return m_end_token;
	}

	void rewind()
	{
		assert(m_token_pos > 0);
		m_token_pos -= 1;
	}

	TokenIdx token_idx() const {
		return TokenIdx(m_token_pos);
	}

	TokenIdx prev_token_idx() const {
		return TokenIdx(m_token_pos > 0 ? m_token_pos - 1 : 0);
	}

	Lexer const& lexer() const {
		return m_lexer;
	}

	string_view get_text(SourceSpan span) const
	{
		size_t start = span.begin.pos;
		size_t end = span.end.pos;
		size_t current_offset = 0;

		// Linear search is okay for now...
		for (string_view source: m_sources)
		{
			if (start < current_offset + source.length())
			{
				// SourceSpans cannot cross source boundaries
				assert(end <= current_offset + source.length());
				return source.substr(start - current_offset, end - start);
			}

			current_offset += source.length();
		}

		assert(!"Invalid SourceSpan");
	}

	size_t bytes_consumed() const
	{
		if (m_token_pos > 0)
			return m_tokens[m_token_pos - 1].span.end.pos;

		return 0;
	}

	void append_source(string_view new_source)
	{
		SourceLocation prev_end = get().span.begin;
		m_tokens.erase(m_tokens.begin() + m_token_pos, m_tokens.end());

		if (m_sources.size())
		{
			string_view &prev_source = m_sources.back();
			size_t unprocessed = (m_lexer.initial_byte_pos() + prev_source.length()) - prev_end.pos;
			prev_source.remove_suffix(unprocessed);
		}

		m_sources.push_back(new_source);
		m_lexer = Lexer(new_source, prev_end);
		fetch_tokens_until(m_token_pos);
	}

private:
	void fetch_tokens_until(size_t pos)
	{
		while(pos >= m_tokens.size())
		{
			if(optional<Token> tok = next_token(m_lexer))
				m_tokens.push_back(*tok);
			else
				break;
		}

		m_end_token.span.begin = m_end_token.span.end = m_lexer.location();
	}

	Lexer m_lexer = {""};
	vector<string_view> m_sources;
	vector<Token> m_tokens;
	size_t m_token_pos = 0; // Index of the next token to be processed

	// It's a member so we can return a reference to it
	Token m_end_token{
		.kind = Lexeme::END,
		.span = {
			.begin = {.pos = 0, .line = 1, .col = 1},
			.end = {.pos = 0, .line = 1, .col = 1},
		},
	};
};


//==============================================================================
// Module
//==============================================================================
class TypeEnv;
struct ConstraintSystem;

class EventLogger
{
public:
	EventLogger(Module *mod, std::ostream &os);
	~EventLogger();

	// Compiler pass events
	void on_declare_items_start();
	void on_declare_items_end();
	void on_resolve_names_start();
	void on_resolve_names_end();
	void on_typecheck_start();
	void on_typecheck_end();
	void on_layout_computation_start();
	void on_layout_computation_end();

	void on_struct_substitution_start(StructInstance *inst);
	void on_struct_substitution_replaced(StructInstance *inst);
	void on_struct_substitution_noop();
	void on_struct_substitution_end();
	void on_struct_layout_computation_start(StructInstance *inst);
	void on_struct_layout_computation_end();
	void on_struct_register(StructInstance *inst);

	void on_proc_register(ProcInstance *inst);
	void on_proc_start(ProcItem *proc);
	void on_proc_end();

	void on_stmt_start(Stmt const &stmt);
	void on_stmt_end();

	void on_expr_start(Expr const &expr);
	void on_expr_end();

	void on_data(TypeEnv const &env);
	void on_data(ConstraintSystem const &sys);

private:
	Module *m_mod;
	std::ostream &m_os;
	vector<Stmt const*> m_stmt_stack;
};

#define LOGGER(logger, event, ...) do { if(logger) (logger)->event(__VA_ARGS__); } while(false)

struct Module
{
	Parser parser;
	ListBuilder<TopLevelItem> items;
	optional<EventLogger> logger{};

	std::unique_ptr<SemaModule> NULLABLE sema{}; // Available after semantic analysis
};

string_view name_of(Parameter const &param, Module const *mod);
void print(TopLevelItem const &item, Module const &mod, std::ostream &os);
void print(Module const &mod, std::ostream &os);

Type parse_type(Parser &parser, Memory M);
TopLevelItem parse_top_level_item(Parser &parser, Memory M);
Module parse_module(string_view source, Memory M);
